apiVersion: v1
kind: Secret
metadata:
  name: lyonflow-secrets
  namespace: default
type: Opaque
stringData:
  # Remplacer par vos vrais identifiants (Kubernetes les encodera automatiquement en Base64)
  API_LOGIN: "votre_login_grand_lyon"
  API_PASSWORD: "votre_mot_de_passe_grand_lyon"
  POSTGRES_USER: "lyonflow"
  POSTGRES_PASSWORD: "lyonflow_password"
  POSTGRES_DB: "lyonflow"
