apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: default
spec:
  ports:
    - port: 8501
      targetPort: 8501
  selector:
    app: streamlit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: lyonflow-app:latest  # Image personnalisée construite localement contenant Streamlit et app.py
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lyonflow-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lyonflow-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: lyonflow-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
          command: ["sh", "-c"]
          args: ["streamlit run app.py --server.port=8501 --server.address=0.0.0.0"]
